project_id = "hoxubepipusimfbkzbxr"

[functions.fetch-book-covers]
verify_jwt = false

[functions.search-books]
verify_jwt = false

[functions.get-book-media]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = true

[functions.lovable-ai-search]
verify_jwt = true

[functions.remove-background]
verify_jwt = true

[functions.enrich-book-data]
verify_jwt = true
